name: Build to Github Pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
       
      - name: Build
        run: npm run build

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # Git branch where assets will be deployed
          target_branch: gh-pages
          # Build directory to deploy
          build_dir: dist
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
